### ISSUE TITLE
NameError: uninitialized constant Chromedriver in rails & rspec config

### ISSUE THREAD

**Issue by yukihr** [flavorjones/chromedriver-helper#65] opened 2018-09-18 03:15 UTC
Calling `Chromedriver.set_version 'XXX'` in rspec config like `rails_helper.rb` causes `NameError: uninitialized constant Chromedriver`.

To resolve this, we need Gemfile line to be like:

```ruby
gem 'chromedriver-helper', require: 'chromedriver/helper'
```

Environment: Rails 5.2.1, chromedriver-helper 2.0.1

**Comment by ibrahima** [comment] 2018-09-18 17:41
Ooh nice, I was trying to figure out how to do this yesterday since Chromedriver uploaded a beta version as the latest version and ran into this same issue. I suppose you could also just manually `require 'chromedriver/helper'` in `rails_helper.rb`?

**Comment by flavorjones** [comment] 2018-09-18 23:38
@yukihr I can update the documentation to reflect this. Are you asking for other action to be taken?

**Comment by flavorjones** [comment] 2018-09-18 23:40
Oh, I understand now. Let me reproduce and update `lib/chromedriver-helper.rb` to require appropriate files.

**Comment by flavorjones** [comment] 2018-09-18 23:47
Will be fixed in v2.0.2 which I'll cut shortly.

**Closed** 2018-09-18 23:47 UTC

**Comment by flavorjones** [comment] 2018-09-19 00:11
Correction, the new release will be v2.1.0.
