### ISSUE TITLE
Add support for the Windows executable

### ISSUE THREAD

**Issue by kevinrood** [flavorjones/chromedriver-helper#19] opened 2015-07-15 16:20 UTC

**Comment by flavorjones** [comment] 2015-09-13 19:32
Hi @kevinrood, thanks for opening this issue.

I'm not sure what you mean here, though, as `chromedriver-helper` has supported Windows forever. Can you provide more information on what's not working for you, as well as information on what version of Windows, Ruby and chromedriver-helper you're using?

**Comment by Christopher-Steel** [comment] 2015-09-15 12:42
Hello @flavorjones,

First of all, very nice gem, I was happy to find it. It's worked perfectly for me both on Linux and on Mac OS. However, on Windows it does not work as smoothly.

I'm on Windows 7, using Git Bash to run the `bundle install` command.
This is my ruby version:
```
$ ruby --version
ruby 2.1.7p400 (2015-08-18 revision 51632) [i386-mingw32]
```
And here is the error printed when I try to run my ruby app after `bundle install`:
```
C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/chrome/service.rb:37:in `executable_path': Unable to find the chromedriver executable. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. (Selenium::WebDriver::Error::WebDriverError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/chrome/service.rb:50:in `default_service'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/chrome/bridge.rb:33:in `initialize'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:56:in `new'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:56:in `for'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver.rb:86:in `for'
        from C:/Users/testaccount/Documents/roach/session.rb:33:in `chrome_open'
        from C:/Users/testaccount/Documents/roach/session.rb:13:in `initialize'
        from C:/Users/testaccount/Documents/roach/roach_test.rb:17:in `new'
        from C:/Users/testaccount/Documents/roach/roach_test.rb:17:in `<main>'```

**Comment by aaronbriel** [comment] 2016-06-15 13:28
I'm seeing this same issue on Windows 10. I've installed chromedriver-helper via gem install. Even with chromedriver.exe in my PATH I see the following error when attempting to run:
Unable to find the chromedriver executable. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. (Selenium::WebDriver::Error::WebDriverError)

**Comment by flavorjones** [comment] 2017-03-15 12:56
I've reproduced this, and I've put a failing integration test on the branch `flavorjones-19-failing-windows-integration-test`.

Unfortunately, I don't know how to make this test pass on Windows, and so I need your help.

Currently if I put a ruby script in `bin/chromedriver.exe`, Windows fails to run it (I see the error as `     Errno::EINVAL: Invalid argument - "chromedriver.exe" -v`). I could make this a powershell script, but it would only work if people had lowered their security settings.

Any ideas on how to make that test pass?

**Comment by flavorjones** [comment] 2018-02-04 00:10
Bumping this, anyone have an idea on what a solution looks like?

**Comment by matti** [comment] 2018-08-27 12:50
could chromedriver add that directory to PATH ?

**Comment by flavorjones** [comment] 2018-09-15 16:41
@matti The question of whether it's in the users `$PATH` doesn't affect the fact that default Windows security settings will not allow running a powershell script.

However, one other potential solution I haven't explored is using `Selenium::WebDriver::Chrome.driver_path` which _might_ allow us to run `powershell.exe` with appropriate args to fire up a script.

**Comment by flavorjones** [comment] 2018-09-15 16:45
Nope, recent versions of Selenium::WebDriver will only accept executables as an argument to `driver_path=`.

Still looking for a solution here.

**Comment by hajarNasr** [comment] 2018-10-06 19:34
@flavorjones  Thank you for your quick response. I am new to codding but since there's not a solution yet I made `Platform.assert_executable path` in drive_path in Chrome.rb as a comment, so it doesn't check whether or not chromedriver-helper is executable anymore. And `rake test` worked but I am not sure if that would break another part in the code?

**Comment by philipfong** [comment] 2018-10-16 03:07
Hey there. I'm on a Windows 7 box and am able to get chromedriver to work on version 1.2.0. However on the latest version of the gem, I get the "not executable" error.

On 1.2.0, I'm able to simply go through a `bundle install`, followed by a `chromedriver-update`. I'm able to run tests using the oddly versioned `70.0.3538.16`. Strangely, forcing 2.42 does NOT work and will produce an error.

It looks like on 1.2.0, `chromedriver.exe` is installed to C:\Users\philipfong\.chromedriver-helper\70.0.3538.16\win directory. Is there a reason that an .exe is not used for the latest version of this gem?

**Comment by flavorjones** [comment] 2018-10-28 20:03
@philipfong I'm not sure what you're asking, and I'm sorry for that.

This issue is describing a problem where, on modern Windowses (which I don't believe includes Windows 7) do not allow the execution of powershell scripts (as a matter of security policy), and so the "shim" script that this gem uses will not execute.

You seem to be describing a different problem, and so I'd like to ask that you open a new issue, please, and start from the beginning when describing what you're seeing. Thank you.

**Comment by shbeavers** [comment] 2018-11-06 04:31
Adding chromedriver.exe to the C:\Windows\System32\ directory gets chromedriver working.  However, this doesn't address why the chromedriver-helper installer isn't working anymore.

 I've seen this problem on two Windows 10 machines where only recently has Ruby been installed along with a very recent version of chromedriver-helper.  With systems that were set up in August, chomedriver-helper's install of Chromedriver functioned perfectly.  These systems continued to work after updating to the latest versions of chromedriver-helper and chromedriver.  The initial installation installed a .chromedriver-helper folder in the C:\Users\UserName directory with chromedriver.exe inside it a couple of folders deep (~\2.40\win\). 

So I'm inclined to ask "what changed?" in the past couple of months to break what had been working.  Meanwhile, I'm content with the simple workaround of manually placing chromedriver.exe in a PATH location.

**Comment by flavorjones** [comment] 2018-11-06 23:34
@shbeavers Thanks for your comment. I've tried to describe the issue above, and it's not due to anything that's changed in the past few months. This issue dates to 2015, and may or may not manifest depending on what security settings are present on your particular windows machines. Pre-Windows-10 this may have worked depending on group policy settings, etc.

Please also note that placing chromedriver.exe in your PATH means you really don't need this gem! Which is great if you're happy with that solution.

**Comment by philipfong** [comment] 2018-11-07 15:46
@flavorjones sorry if I was unclear. What I was getting at was that using version 1.2.0 on Windows 7 works just fine whereas the latest version of the gem does not.

If you need steps to reproduce, simply run `gem install chromedriver-helper` then a `chromedriver-update` and failures will happen when attempting to run tests on Windows 7. However on 1.2.0 things work just fine.

I'm with @shbeavers in pretty much asking "what changed?"

**Comment by whatisc** [comment] 2018-11-09 06:58
The only solution for me is to use 1.2.0.

**Comment by flavorjones** [comment] 2018-11-14 03:51
Hi all,

If something's not working that's changed since v1.2.0 then can someone please open a __new__ ticket and we can dig in there? Again, this ticket was opened to describe an issue related to Windows 10 file permissioning that's existed for several years, and v1.2.0 was released earlier in Feb 2018.

Having a second (or third) issue here makes this information harder to find, so thank you in advance for helping me out and opening a new issue.

**Comment by whatisc** [comment] 2018-11-14 03:55
I read changing this
```
     def assert_executable(path)
        assert_file(path)

        return if File.executable? path
        raise Error::WebDriverError, "not executable: #{path.inspect}"
      end

```

To this
```
     def assert_executable(path)
        assert_file(path)

        return nil
        raise Error::WebDriverError, "not executable: #{path.inspect}"
      end
```

Also addresses the issue. So maybe that's a place to start?

**Comment by GrayStrider** [comment] 2018-11-30 00:24
> I read changing this
> 
> ```
>      def assert_executable(path)
>         assert_file(path)
> 
>         return if File.executable? path
>         raise Error::WebDriverError, "not executable: #{path.inspect}"
>       end
> ```
> To this
> 
> ```
>      def assert_executable(path)
>         assert_file(path)
> 
>         return nil
>         raise Error::WebDriverError, "not executable: #{path.inspect}"
>       end
> ```
> Also addresses the issue. So maybe that's a place to start?

Had this problem, worked. Thanks

**Comment by flavorjones** [comment] 2019-03-25 13:13
I'm going to close this issue, as the gem is being deprecated in favor of webdrivers, see #83.

**Closed by flavorjones** 2019-03-25 13:13 UTC
Labels: needs a solution
